#!/bin/bash

# INFO: THIS SCRIPT GENERATES TWO IMAGES, ONE DARK AND ONE LIGHT, TO BE USED AS WALLPAPERS FOR THEME MODE ON MACOS

# USAGE: BEFORE EXECUTING THIS SCRIPT, MAKE SURE TO GIVE IT EXECUTION PERMISSION:
#        RUN THE FOLLOWING COMMAND IN YOUR TERMINAL:
#        chmod +x generate_color_images_theme.sh

# DEFINITION OF PARAMETERS
WIDTH=3024
HEIGHT=1964
DARK_COLOR="#202020"
LIGHT_COLOR="#FFFFFF"

# CHECK IF IMAGEMAGICK IS INSTALLED
if ! command -v magick &>/dev/null; then
    echo "❌ ERROR: IMAGEMAGICK (MAGICK) IS NOT INSTALLED. INSTALL IT WITH: BREW INSTALL IMAGEMAGICK"
    exit 1
fi

# GENERATE IMAGES WITH IMAGEMAGICK
magick -size ${WIDTH}x${HEIGHT} xc:"$DARK_COLOR" dark_mode.png || {
    echo "❌ ERROR GENERATING DARK_MODE.PNG"
    exit 1
}
magick -size ${WIDTH}x${HEIGHT} xc:"$LIGHT_COLOR" light_mode.png || {
    echo "❌ ERROR GENERATING LIGHT_MODE.PNG"
    exit 1
}

# DISPLAY A MESSAGE INDICATING THAT IMAGES HAVE BEEN GENERATED
echo "✅ IMAGES GENERATED: DARK_MODE.PNG & LIGHT_MODE.PNG"
